name: OpenCart
type: app
description: The best free and open-source eCommerce platform. Everything you need to create, scale and run your business.
serviceNames:
  - php
  - mysql
mappings:
  - path: /
    matchPattern: begins-with
    targetType: service
    targetServiceName: php
dataFields:
  - key: ocUser
    isRequired: true
  - key: ocPassword
    isRequired: true
  - key: ocEmail
    isRequired: true
cmdSteps:
  - wget -O /speedia/opencart.zip https://github.com/opencart/opencart/releases/download/4.0.2.3/opencart-4.0.2.3.zip
  - unzip /speedia/opencart.zip
  - mv /speedia/opencart-*/upload/* %installDirectory% && rm -rf /speedia/opencart*
  - mv %installDirectory%/config-dist.php %installDirectory%/config.php && chmod 0777 %installDirectory%/config.php
  - mv %installDirectory%/admin/config-dist.php %installDirectory%/admin/config.php && chmod 0777 %installDirectory%/admin/config.php
  - sos runtime php update -v 82 -S allow_url_fopen -V on
  - sos db create -n ocDb_%installUuid% -t mysql
  - echo $(openssl rand -hex 8) > %installDirectory%/ocDbCredentials
  - sos db create-user -n ocDb_%installUuid% -t mysql -u ocUser_%installUuid% -p $(cat %installDirectory%/ocDbCredentials) -r all
  - php %installDirectory%/install/cli_install.php install --username %ocUser% --password %ocPassword% --email %ocEmail% --http_server http://%installHostname%/ --db_driver mysqli --db_hostname localhost --db_username ocUser_%installUuid% --db_password $(cat %installDirectory%/ocDbCredentials) --db_database ocDb_%installUuid% --db_port 3306 --db_prefix oc_
  - rm -rf %installDirectory%/ocDbCredentials
estimatedSizeBytes: 1000000000
avatarUrl: "https://speedia.net/assets/os/marketplace/opencart/oc-avatar.jpg"
screenshotUrls:
  - "https://speedia.net/assets/os/marketplace/opencart/oc-1.jpg"
  - "https://speedia.net/assets/os/marketplace/opencart/oc-2.jpg"
