name: OpenCart
type: app
description: The best free and open-source eCommerce platform. Everything you need to create, scale and run your business.
serviceNames:
  - php
  - mysql
mappings:
  - path: /
    matchPattern: begins-with
    targetType: service
    targetServiceName: php
cmdSteps:
  - wget -O /speedia/opencart.zip https://github.com/opencart/opencart/releases/download/4.0.2.3/opencart-4.0.2.3.zip
  - unzip /speedia/opencart.zip
  - mv /speedia/opencart-*/upload/* %installDirectory% && rm -rf /speedia/opencart*
  - mv %installDirectory%/config-dist.php %installDirectory%/config.php && chmod 0777 %installDirectory%/config.php
  - mv %installDirectory%/admin/config-dist.php %installDirectory%/admin/config.php && chmod 0777 %installDirectory%/admin/config.php
  - sos db create -n openCartDb_%installUuid% -t mysql
  - echo $(openssl rand -hex 8) > %installDirectory%/openCartDbCredentials
  - sos db create-user -n openCartDb_%installUuid% -t mysql -u openCartUser_%installUuid% -p $(cat %installDirectory%/openCartDbCredentials) -r all
  - echo -e "<?php\ndefine('DB_DRIVER', 'mysqli');\ndefine('DB_HOSTNAME', 'localhost');\ndefine('DB_USERNAME', 'openCartUser_%installUuid%');\ndefine('DB_PASSWORD', '$(cat %installDirectory%/openCartDbCredentials)');\ndefine('DB_DATABASE', 'openCartDb_%installUuid%');\n?>" > %installDirectory%/config.php
  - echo -e "<?php\ndefine('DB_DRIVER', 'mysqli');\ndefine('DB_HOSTNAME', 'localhost');\ndefine('DB_USERNAME', 'openCartUser_%installUuid%');\ndefine('DB_PASSWORD', '$(cat %installDirectory%/openCartDbCredentials)');\ndefine('DB_DATABASE', 'openCartDb_%installUuid%');\n?>" > %installDirectory%/admin/config.php
  - rm -rf %installDirectory%/openCartDbCredentials
estimatedSizeBytes: 1000000000
avatarUrl: "https://speedia.net/assets/os/marketplace/opencart/oc-avatar.jpg"
screenshotUrls:
  - "https://speedia.net/assets/os/marketplace/opencart/oc-1.jpg"
  - "https://speedia.net/assets/os/marketplace/opencart/oc-2.jpg"
