name: java-webserver
slugs:
  - java
  - jdk
  - openjdk
  - tomcat
nature: solo
type: runtime
description: Java is a multiplatform, object-oriented programming language that runs on billions of devices worldwide. It powers applications, smartphone operating systems, enterprise software, and many well-known programs.
versions:
  - 11
  - 17
  - 21
portBindings:
  - 8080/http
  - 8443/https
startCmd: /opt/tomcat/bin/catalina.sh start
installCmdSteps:
  - mise install java@%version%
  - chmod +x $(mise where java)
  - ln -s $(mise where java) /usr/bin/java
  - mkdir -p /opt/tomcat
  - curl -sKL -o /tmp/tomcat.tar.gz https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.93/bin/apache-tomcat-9.0.93.tar.gz
  - tar -xzf /tmp/tomcat.tar.gz -C /opt/tomcat --strip-components=1
  - rm /tmp/tomcat.tar.gz
  - chown -R nobody:nogroup /opt/tomcat
  - chmod +x /opt/tomcat/bin/*.sh
  - ln -s /opt/tomcat/bin/catalina.sh /usr/bin/tomcat
uninstallCmdSteps:
  - mise uninstall java
  - rm -rf /opt/tomcat
  - unlink /usr/local/bin/tomcat
stopCmdSteps:
  - /opt/tomcat/bin/shutdown.sh
execUser: root
estimatedSizeBytes: 500000000
